language: go

git:
  depth: 1

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go get github.com/mattn/goveralls

install:
  - dep ensure -vendor-only -v

script:
  - go test -v  ./...
go:
  - 1.10.x