required = ["github.com/op/go-logging"]

[[override]]
  name = "github.com/hyperledger/fabric"
  version = "1.4.0"


[[override]]
  name = "github.com/golang/protobuf"
  branch = "master"


[[override]]
  name = "github.com/pkg/errors"
  branch = "master"


[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[override]]
  name = "github.com/fsouza/go-dockerclient"
  version = "=1.2.1"